import json
from pathlib import Path

nb_path = Path(r'c:\Users\Thatr\Documents\RAG\RAG_Project_Larry.ipynb.ipynb')
with nb_path.open('r', encoding='utf-8') as f:
    nb = json.load(f)
new_source = [
    "class RAGAssistant:",
    "    \"\"\"RAG-powered knowledge assistant that retrieves context and validates answers.\"\"\"",
    "",
    "    def __init__(self, collection, qa_model, confidence_threshold: float = 0.3):",
    "        \"\"\"Initialize the RAG assistant.",
    "",                
    "        Args:",
    "            collection: ChromaDB collection containing embedded document chunks.",
    "            qa_model: Extractive QA model or wrapper that accepts question/context inputs.",
    "            confidence_threshold: Minimum combined confidence to return a direct answer.",
    "        \"\"\"",
    "        self.collection = collection",
    "        self.qa_model = qa_model",
    "        self.confidence_threshold = confidence_threshold",
    "",
    "    def retrieve(self, query: str, n_results: int = 3) -> Dict:",
    "        \"\"\"Retrieve relevant document chunks from the vector database.",
    "",                
    "        Args:",
    "            query: Question text used for semantic retrieval.",
    "            n_results: Number of top documents to return.",
    "",                
    "        Returns:",
    "            Dictionary containing retrieved documents, metadatas, and distance scores.",
    "        \"\"\"",
    "        results = self.collection.query(",
    "            query_texts=[query],",
    "            n_results=n_results,",
    "            include=[\"documents\", \"metadatas\", \"distances\"]",
    "        )",
    "        return results",
    "",
    "    def generate_answer(self, question: str, context: str) -> Dict:",
    "        \"\"\"Generate an extractive answer from retrieved context text.",
    "",                
    "        The model returns logits for start and end token positions. The selected",
    "        answer span is decoded from the token indices and converted into a",
    "        normalized confidence score.",
    "",                
    "        Args:",
    "            question: The original user question.",
    "            context: Consolidated text retrieved from the knowledge base.",
    "",                
    "        Returns:",
    "            Dictionary with the extracted answer text and model confidence score.",
    "        \"\"\"",
    "        extraction = self.qa_model(question=question, context=context)",
    "        extracted_text = extraction[\"answer\"].strip()",
    "        confidence = extraction.get(\"score\", 0.0)",
    "",
    "        if not extracted_text or len(extracted_text) <= 1 or extracted_text.lower() in question.lower():",
    "            return {",
    "                \"answer\": \"I do not have enough information in the knowledge base to answer that.\",
    "                \"confidence\": 0.0",
    "            }",
    "",
    "        return {",
    "            \"answer\": extracted_text,",
    "            \"confidence\": confidence",
    "        }",
    "",
    "    def ask(self, question: str, n_results: int = 3) -> Dict:",
    "        \"\"\"Run the complete RAG pipeline and return a validated answer.",
    "",                
    "        The method retrieves relevant documents, generates a candidate answer,",
    "        and applies a reliability gate based on retrieval alignment and model confidence.",
    "",                
    "        Args:",
    "            question: The user's question.",
    "            n_results: Number of documents to retrieve from ChromaDB.",
    "",                
    "        Returns:",
    "            Dictionary containing the question, final answer, confidence score,",
    "            source metadata, and a confidence flag.",
    "        \"\"\"",
    "        retrieval_results = self.retrieve(question, n_results=n_results)",
    "        retrieved_docs = retrieval_results.get(\"documents\", [[]])[0]",
    "        retrieved_metadatas = retrieval_results.get(\"metadatas\", [[]])[0]",
    "        retrieved_distances = retrieval_results.get(\"distances\", [[]])[0]",
    "",
    "        fallback_answer = \"I'm sorry, but I do not have enough confident information in my knowledge base to accurately answer this question.\"",
    "",
    "        if not retrieved_docs:",
    "            return {",
    "                \"question\": question,",
    "                \"answer\": fallback_answer,",
    "                \"confidence\": 0.0,",
    "                \"sources\": [],",
    "                \"is_confident\": False",
    "            }",
    "",
    "        context = \"\\n\\n\".join(retrieved_docs)",
    "        generated = self.generate_answer(question, context)",
    "",
    "        avg_distance = sum(retrieved_distances) / len(retrieved_distances) if retrieved_distances else 1.0",
    "        retrieval_confidence = max(0.0, 1.0 - avg_distance)",
    "        final_confidence = min(generated[\"confidence\"], retrieval_confidence)",
    "        is_confident = final_confidence >= self.confidence_threshold",
    "",
    "        sources: list[str] = []",
    "        for meta in retrieved_metadatas:",
    "            title = meta.get(\"title\", meta.get(\"source\", \"Unknown Source\"))",
    "            if title not in sources:",
    "                sources.append(title)",
    "",
    "        final_answer = generated[\"answer\"].strip()",
    "        if not final_answer or not is_confident:",
    "            final_answer = fallback_answer",
    "            is_confident = False",
    "            final_confidence = 0.0",
    "",
    "        return {",
    "            \"question\": question,",
    "            \"answer\": final_answer,",
    "            \"confidence\": final_confidence,",
    "            \"sources\": sources,",
    "            \"is_confident\": is_confident",
    "        }",
    "",
    "    def format_response(self, result: Dict) -> str:",
    "        \"\"\"Format the pipeline result into a user-friendly response string.",
    "",                
    "        Args:",
    "            result: Output returned by the ask method.",
    "",                
    "        Returns:",
    "            Formatted response string with confidence and source details.",
    "        \"\"\"",
    "        status = \"✅\" if result[\"is_confident\"] else \"⚠️\"",
    "        response = f\"{status} Question: {result['question']}\\n\\n\"",
    "        response += f\"Answer: {result['answer']}\\n\\n\"",
    "        response += f\"Confidence: {result['confidence']:.2%}\\n\"",
    "",
    "        if result[\"sources\"]:",
    "            response += f\"Sources: {', '.join(result['sources'])}\"",
    "        else:",
    "            response += \"Sources: None\"",
    "",
    "        return response",
    "",
    "",
    "assistant = RAGAssistant(collection, generator, confidence_threshold=0.3)",
    "",
    "print(\"✅ RAG Assistant created!\")"
]

cell_found = False
for cell in nb['cells']:
    if cell.get('id') == '#VSC-1183ab2d':
        cell['source'] = new_source
        cell_found = True
        break

if not cell_found:
    raise ValueError('RAGAssistant cell not found')

with nb_path.open('w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('updated')
